name: run-tests

on:
  push:
    branches: 
      - 'autotest**'
  pull_request:
    branches: 
      - 'autotest**'
      - 'release'
  workflow_dispatch:
    value: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: Run tests on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.9.2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose